# Generated by Django 3.0.11 on 2021-09-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210919_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratkeluar',
            name='department',
            field=models.ManyToManyField(blank=True, to='app.Department'),
        ),
        migrations.AlterField(
            model_name='suratkeluar',
            name='file',
            field=models.ManyToManyField(blank=True, to='app.File'),
        ),
    ]
