# Generated by Django 3.0.11 on 2021-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210920_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='arsip',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suratkeluar',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
