# Generated by Django 3.0.11 on 2021-09-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210922_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratkeluar',
            name='isArsip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suratmasuk',
            name='isArsip',
            field=models.BooleanField(default=False),
        ),
    ]
