# Generated by Django 3.0.11 on 2021-09-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210922_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsip',
            name='file_path',
            field=models.ManyToManyField(blank=True, to='app.File'),
        ),
    ]
