# Generated by Django 3.0.11 on 2021-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210922_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='arsip',
            name='created_at',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ManyToManyField(related_name='note', to='app.Pengguna'),
        ),
        migrations.AlterField(
            model_name='suratkeluar',
            name='created_at',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='created_at',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
