# Generated by Django 3.0.11 on 2021-09-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210923_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratkeluar',
            name='department',
        ),
    ]
