# Generated by Django 3.0.11 on 2021-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_suratkeluar_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
